package com.variamos.dynsup.types;

/**
 * An enumeration to represent possible components of a Transformation. Part of
 * PhD work at University of Paris 1
 * 
 * @author Juan C. Muñoz Fernández <jcmunoz@gmail.com>
 * 
 * @version 1.1
 * @since 2014-12-14
 */
public enum ExpressionVertexType {
	LEFTVARIABLE, RIGHTVARIABLE, LEFTBOOLEANEXPRESSION, RIGHTBOOLEANEXPRESSION, LEFTNUMERICVALUE, RIGHTNUMERICVALUE, LEFTSUBEXPRESSION, RIGHTSUBEXPRESSION, LEFTVARIABLEVALUE, RIGHTVARIABLEVALUE, LEFTSTRINGVALUE, RIGHTSTRINGVALUE, LEFTMODELVARS, RIGHTMODELVARS, LEFTCONCEPTVARIABLE, RIGHTCONCEPTVARIABLE, LEFTITERCONFIXEDVARIABLE, LEFTITERINCCONFIXEDVARIABLE, LEFTITEROUTCONFIXEDVARIABLE, LEFTITERINCRELFIXEDVARIABLE, LEFTITEROUTRELFIXEDVARIABLE, LEFTITERANYFIXEDVARIABLE, LEFTITERCONCEPTVARIABLE, LEFTITERINCRELVARIABLE, LEFTITEROUTRELVARIABLE, LEFTITERINCCONVARIABLE, LEFTITEROUTCONVARIABLE, LEFTITERANYCONVARIABLE, LEFTITERANYRELVARIABLE, LEFTUNIQUEINCRELVARIABLE, RIGHTUNIQUEINCRELVARIABLE, LEFTUNIQUEOUTRELVARIABLE, RIGHTUNIQUEOUTRELVARIABLE, LEFTUNIQUEINCCONVARIABLE, RIGHTUNIQUEINCCONVARIABLE, LEFTUNIQUEOUTCONVARIABLE, RIGHTUNIQUEOUTCONVARIABLE
}
