package com.variamos.dynsup.types;

/**
 * An enumeration to represent possible components of a Transformation. Part of
 * PhD work at University of Paris 1
 * 
 * @author Juan C. Muñoz Fernández <jcmunoz@gmail.com>
 * 
 * @version 1.1
 * @since 2014-12-14
 */

// @formatter:off
public enum ExpressionVertexType {

	LEFTVARIABLE, RIGHTVARIABLE,

	LEFTNUMERICVALUE, RIGHTNUMERICVALUE,

	LEFTVARIABLEVALUE, RIGHTVARIABLEVALUE,

	LEFTSTRINGVALUE, RIGHTSTRINGVALUE,

	LEFTMODELVARS, RIGHTMODELVARS,

	RIGHTNUMERICFLOATVALUE,

	LEFTCONCEPTVARIABLE, RIGHTCONCEPTVARIABLE,

	// Sub Expressions
	LEFTSUBEXPRESSION, RIGHTSUBEXPRESSION,

	LEFTBOOLEANEXPRESSION, RIGHTBOOLEANEXPRESSION,

	// Iter with subexpressions - not working
	LEFTITERINCSUBEXP, LEFTITEROUTSUBEXP, LEFSUBTITERINCSUBEXP, LEFTSUBITEROUTSUBEXP,

	// Pairwise relations
	LEFTUNIQUEOUTCONVARIABLE, LEFTUNIQUEINCCONVARIABLE,

	RIGHTUNIQUEINCCONVARIABLE, RIGHTUNIQUEOUTCONVARIABLE,

	// not used
	LEFTUNIQUEINCRELVARIABLE, LEFTUNIQUEOUTRELVARIABLE,

	RIGHTUNIQUEOUTRELVARIABLE, RIGHTUNIQUEINCRELVARIABLE,

	// All model
	LEFTITERCONCEPTVARIABLE, LEFSUBTITERCONVARIABLE,

	// OverTwo relations
	LEFTITERANYCONVARIABLE, LEFTITERINCCONVARIABLE, LEFTITEROUTCONVARIABLE,

	LEFTSUBITERANYVARIABLE, LEFTSUBITERINCCONVARIABLE, LEFTSUBITEROUTCONVARIABLE,

	LEFTITERANYRELVARIABLE, LEFTITERINCRELVARIABLE, LEFTITEROUTRELVARIABLE,

	LEFTSUBITERANYRELVARIABLE, LEFTSUBITERINCRELVARIABLE, LEFTSUBITEROUTRELVARIABLE

}
