package com.variamos.dynsup.types;

//FIXME move to an OMMEnum
public enum PerspectiveType {
	MODELING, SYNTAXSUPERSTRUCTURE, OPERATIONSSUPERSTRUCTURE, CONFIG_SIMULATION, SYNTAXINFRASTRUCTURE, OPERATIONSINFRASTRUCTURE, INFRASTRUCTUREBASICSYNTAX
}
