:-use_module(library(clpfd)).
productline(L):-
L=[Celular,Utilidades,LLamadas,Mensajes,MSN,SMS,
Juegos,Configuracion,SO,Soporte_Java,Multimedia,MP3,MP4,Camara,VGA,Mexapixeles],
L ins 0..1,
Celulares #= 1,
Mexapixeles#= 1,
Celulares#<==>Utilidades,
Utilidades#<==>LLamadas,
Utilidades#<==>Juegos,
Celulares#<==>Configuracion,
Configuracion#<==>SO,
Configuracion#<==>Soporte_Java,
Utilidades#>=Mensajes,
Celulares#>=Multimedia,
Multimedia#>=MP3,
Multimedia#>=MP4,
Multimedia#>=Camara,
Soporte_Java#==> VGA,
SO * Mexapixeles#=0,
1 * Mensajes #=< SMS + MSN,
SMS + MSN #=< 2 * Mensajes,
1 * Camara #= Mexapixeles + VGA,
label(L).
