productline(L):-
fd_set_vector_max(10010),
L = [Var_Bicycle, Var_Frame, Var_Iron, Var_Aluminum, Var_Carbon, Var_White, Var_Red, Var_Black, Var_Gears, Var_Front, Var_Rear, Var_Wheels, Var_Saddle, Var_Color, Var_Red, Var_Green, Var_Blue, Var_Handle_bars, Var_Pedals, Var_Warranty, Var_1_year, Var_2_years, Var_3_years, Var_Maintenance_plan, Var_2_years, Var_3_years, Var_Lifetime],
fd_domain([Var_Bicycle, Var_Frame, Var_Iron, Var_Aluminum, Var_Carbon, Var_White, Var_Red, Var_Black, Var_Gears, Var_Front, Var_Rear, Var_Wheels, Var_Saddle, Var_Color, Var_Red, Var_Green, Var_Blue, Var_Handle_bars, Var_Pedals, Var_Warranty, Var_1_year, Var_2_years, Var_3_years, Var_Maintenance_plan, Var_2_years, Var_3_years, Var_Lifetime], 0, 1),
Var_Bicycle #= 1, Var_Bicycle #<=> Var_Frame,
Var_Bicycle #<=> Var_Wheels,
Var_Bicycle #<=> Var_Saddle,
Var_Bicycle #<=> Var_Color,
Var_Bicycle #<=> Var_Handle_bars,
Var_Bicycle #<=> Var_Gears #>= 1,
Var_Gears #<=> Var_Front #>= 1,
Var_Gears #<=> Var_Rear #>= 1,
Var_Bicycle #<=> Var_Pedals #>= 1,
Var_Bicycle #<=> Var_Warranty #>= 1,
Var_Bicycle #<=> Var_Maintenance_plan #>= 1,
(1 - Var_Front) + Var_Rear #> 0,
(1 - Var_Carbon) + Var_Red #> 0,
1 * Var_Frame #= Var_Carbon + Var_Aluminum + Var_Iron,
1 * Var_Carbon #= Var_Black + Var_Red + Var_White,
1 * Var_Color #= Var_Blue + Var_Green + Var_Red,
1 * Var_Warranty #= Var_3_years + Var_2_years + Var_1_year,
1 * Var_Maintenance_plan #= Var_Lifetime + Var_3_years + Var_2_years,
fd_labeling(L).

