productline(L):-
fd_set_vector_max(10010),
L = [Var_Cell_phone, Var_Basis_Functions, Var_Message, Var_SMS, Var_MMS, Var_Voice_Call, Var_Communication, Var_WLAN, Var_Bluetooth, Var_UMTS, Var_Extras, Var_MP3, Var_Camera, Var_3MP, Var_8MP],
fd_domain([Var_Cell_phone, Var_Basis_Functions, Var_Message, Var_SMS, Var_MMS, Var_Voice_Call, Var_Communication, Var_WLAN, Var_Bluetooth, Var_UMTS, Var_Extras, Var_MP3, Var_Camera, Var_3MP, Var_8MP], 0, 1),
Var_Cell_phone #= 1, Var_Cell_phone #<=> Var_Basis_Functions,
Var_Basis_Functions #<=> Var_Message,
Var_Message #<=> Var_SMS,
Var_Basis_Functions #<=> Var_Voice_Call,
Var_Cell_phone #<=> Var_Extras,
Var_Message #<=> Var_MMS #>= 0,
Var_Cell_phone #<=> Var_Communication #>= 0,
Var_Communication #<=> Var_WLAN #>= 0,
Var_Communication #<=> Var_Bluetooth #>= 0,
Var_Communication #<=> Var_UMTS #>= 0,
(1 - Var_MMS) + Var_Camera #> 0,
(1 - Var_Bluetooth) + (1 - Var_MP3) #> 0,
1 * Var_Extras #=< Var_Camera + Var_MP3,
Var_Camera + Var_MP3 #=< 2 * Var_Extras,
1 * Var_Camera #= Var_8MP + Var_3MP,
fd_labeling(L).
