package com.variamos.refas.core.types;

public enum ExpressionClassType {
AndBooleanTransformation, AssignBooleanTransformation,DiffNumericTransformation,DoubleImplicationBooleanTransformation,
EqualsComparisonTransformation,GreaterOrEqualsBooleanTransformation,ImplicationBooleanTransformation,LessBooleanTransformation,
LessOrEqualsBooleanTransformation,LiteralBooleanTransformation,NotBooleanTransformation,NotEqualsBooleanTransformation,
NumberNumericTransformation,OrBooleanTransformation,ProdNumericTransformation,SumNumericTransformation
}
